using VisionTestAI.Domain.Enums;

namespace VisionTestAI.Domain.Entities;

/// <summary>
/// Represents a single action step in a test plan (generated by AI).
/// This is a value object typically serialized as part of TestPlanJson.
/// </summary>
public class TestStep
{
    public int Order { get; set; }
    public StepAction Action { get; set; }
    public string? Selector { get; set; }
    public string? Value { get; set; }
    public string Description { get; set; } = string.Empty;
    public string DescriptionAr { get; set; } = string.Empty;
}
